javax:
  sql:
    DataSource:
      ecommerceDataSource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          url: jdbc:postgresql://localhost:5432/postgres
          username: postgres
          password: 123456
