javax:
  sql:
    DataSource:
      ecommerceDataSource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          url: jdbc:postgresql://postgres:5432/postgres
          user: postgres
          password: 123456
