/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.programacion.ecommerce;

import java.util.concurrent.TimeUnit;

import io.helidon.webserver.Routing;
import io.helidon.webserver.WebServer;
import io.helidon.webserver.staticcontent.StaticContentSupport;

public class App {
    public static void main(String[] args) {
        WebServer webServer = WebServer
                .create(Routing.builder().register("/",
                        StaticContentSupport.builder("/dist").welcomeFileName("index.html").build()))
                .start().await(10, TimeUnit.SECONDS);

        System.out.println("Server started at: http://localhost:" + webServer.port());
    }
}
